# -*- coding: utf-8 -*-
"""plot_clustered_graph

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PwsivLHFkzRvy4FwL8Rv5rJ3i8d21LjQ
"""

import networkx as nx 
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np

def plotgraph(cluster_no,edgedata):
  partition=dict(enumerate(cluster_no))
  edge_data = pd.DataFrame(edgedata, columns=["node1", "node2","weight"])
  g = nx.Graph()
  g = nx.from_pandas_edgelist(df, source='node1', target='node2', edge_attr ='weight',)
  # visualization
  plt.figure(figsize=(20,16))
  plt.grid(False)
  pos=nx.spring_layout(g)
  cmap = cm.get_cmap('plasma', max(partition.values()) + 1)
  nx.draw_networkx_nodes(g, pos, partition.keys(), node_size=50,cmap=cmap, node_color=list(partition.values()))
  nx.draw_networkx_edges(g, pos, alpha=0.5)
  plt.savefig("clustered_graph_spring_layout.png")